version: '3'
services:
  app:
    container_name: bws-node-api
    restart: always
    build: .
    ports:
      - '3000:3000'
      - '9229:9229'
    external_links:
      - mongo
  mongo:
    container_name: bws-mongo
    image: mongo
    ports:
      - '27017:27017'
